//
//  SessionPending.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class SessionPending: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _sessionID: NSNumber?
    var _courseCode: String?
    var _courseSubject: NSNumber?
    var _endTime: NSNumber?
    var _location: String?
    var _notes: String?
    var _startTime: NSNumber?
    var _student: String?
    var _studentRequestedTime: NSNumber?
    var _tutor: String?
    var _tutorAcceptedTime: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "tutortonight-mobilehub-1959870186-session_pending"
    }
    
    class func hashKeyAttribute() -> String {

        return "_sessionID"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_sessionID" : "sessionID",
               "_courseCode" : "courseCode",
               "_courseSubject" : "courseSubject",
               "_endTime" : "endTime",
               "_location" : "location",
               "_notes" : "notes",
               "_startTime" : "startTime",
               "_student" : "student",
               "_studentRequestedTime" : "studentRequestedTime",
               "_tutor" : "tutor",
               "_tutorAcceptedTime" : "tutorAcceptedTime",
        ]
    }
}
