//
//  SessionCompleted.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class SessionCompleted: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _sessionID: String?
    var _actualEndTime: NSNumber?
    var _actualStartTime: NSNumber?
    var _courseCode: NSNumber?
    var _courseSubject: String?
    var _endTime: NSNumber?
    var _location: String?
    var _notes: String?
    var _startTime: NSNumber?
    var _student: String?
    var _studentRating: NSNumber?
    var _studentRequestedTime: NSNumber?
    var _studentReview: String?
    var _tutor: String?
    var _tutorAcceptedTime: NSNumber?
    var _tutorRating: NSNumber?
    var _tutorReview: String?
    
    class func dynamoDBTableName() -> String {

        return "tutortonight-mobilehub-1959870186-session_completed"
    }
    
    class func hashKeyAttribute() -> String {

        return "_sessionID"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_sessionID" : "sessionID",
               "_actualEndTime" : "actualEndTime",
               "_actualStartTime" : "actualStartTime",
               "_courseCode" : "courseCode",
               "_courseSubject" : "courseSubject",
               "_endTime" : "endTime",
               "_location" : "location",
               "_notes" : "notes",
               "_startTime" : "startTime",
               "_student" : "student",
               "_studentRating" : "studentRating",
               "_studentRequestedTime" : "studentRequestedTime",
               "_studentReview" : "studentReview",
               "_tutor" : "tutor",
               "_tutorAcceptedTime" : "tutorAcceptedTime",
               "_tutorRating" : "tutorRating",
               "_tutorReview" : "tutorReview",
        ]
    }
}
