//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import UIKit
import AWSMobileHubHelper

class MainViewController: UITableViewController {
    
    var demoFeatures: [DemoFeature] = []
    var willEnterForegroundObserver: AnyObject!
    
    // MARK: - View lifecycle
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .Plain, target: nil, action: nil)
        
        // You need to call `- updateTheme` here in case the sign-in happens before `- viewWillAppear:` is called.
        updateTheme()
        willEnterForegroundObserver = NSNotificationCenter.defaultCenter().addObserverForName(UIApplicationWillEnterForegroundNotification, object: nil, queue: NSOperationQueue.currentQueue()) { _ in
            self.updateTheme()
        }
        
        
        var demoFeature = DemoFeature.init(
            name: NSLocalizedString("Account Details",
            comment: "View your user credentials."),
            detail: NSLocalizedString("Enable user login with popular 3rd party providers.",
            comment: "Description for demo menu option."),
            icon: "UserIdentityIcon",
            storyboard: "accountSeg"
        )
        
        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Push Notifications",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("Send individual or group push notifications to your apps.",
                comment: "Manage your push notification settings."),
            icon: "PushIcon",
            storyboard: "pushSeg"
        )
        
        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Payment ",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("Store and distribute media assets and other files via global content delivery network.",
                comment: "Manage your payment information."),
            icon: "ContentDeliveryIcon",
            storyboard: "paymentSeg"
        )
        
        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("Transcript",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("View your verified courses.",
                comment: "Description for demo menu option."),
            icon: "UserFilesIcon",
            storyboard: "courseSeg"
        )
        
        demoFeatures.append(demoFeature)
        
        //        demoFeature = DemoFeature.init(
        //            name: NSLocalizedString("App Analytics",
        //                comment: "Label for demo menu option."),
        //            detail: NSLocalizedString("Collect, visualize and export app usage metrics.",
        //            comment: "Description for demo menu option."),
        //            icon: "AppAnalyticsIcon")
        //
        //        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("About Us",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("App version, changelog, etc.",
                comment: "Description for demo menu option."),
            icon: "CloudLogicIcon",
            storyboard: "aboutSeg"
        )
        
        demoFeatures.append(demoFeature)
        
    }
    
    deinit {
        NSNotificationCenter.defaultCenter().removeObserver(willEnterForegroundObserver)
    }
    
    
    // MARK: - UITableViewController delegates
    
    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCellWithIdentifier("MainViewCell")!
        let demoFeature = demoFeatures[indexPath.row]
        cell.imageView!.image = UIImage(named: demoFeature.icon)
        cell.textLabel!.text = demoFeature.displayName
        cell.detailTextLabel!.text = demoFeature.detailText
        return cell
    }
    
    override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return demoFeatures.count
    }
    
    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        tableView.deselectRowAtIndexPath(indexPath, animated: true)
        let demoFeature = demoFeatures[indexPath.row]
        //        let storyboard = UIStoryboard(name: demoFeature.storyboard, bundle: nil)
        //        let viewController = storyboard.instantiateViewControllerWithIdentifier(demoFeature.storyboard)
        //        self.navigationController!.pushViewController(viewController, animated: true)
        self.performSegueWithIdentifier(demoFeature.storyboard, sender: nil)
    }
    
    func updateTheme() {
        let settings = ColorThemeSettings.sharedInstance
        settings.loadSettings { (themeSettings: ColorThemeSettings?, error: NSError?) -> Void in
            guard let themeSettings = themeSettings else {
                print("Failed to load color: \(error)")
                return
            }
            dispatch_async(dispatch_get_main_queue(), {
                let titleTextColor: UIColor = themeSettings.theme.titleTextColor.UIColorFromARGB()
                self.navigationController!.navigationBar.barTintColor = themeSettings.theme.titleBarColor.UIColorFromARGB()
                self.view.backgroundColor = themeSettings.theme.backgroundColor.UIColorFromARGB()
                self.navigationController!.navigationBar.tintColor = titleTextColor
                self.navigationController!.navigationBar.titleTextAttributes = [NSForegroundColorAttributeName: titleTextColor]
            })
        }
    }
}

class FeatureDescriptionViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem.init(title: "Back", style: .Plain, target: nil, action: nil)
    }
}
