//
//  CourseYearID.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class CourseYearID: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _courseLevelID: NSNumber?
    var _subject: String?
    var _year: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "tutortonight-mobilehub-1959870186-course_year_ID"
    }
    
    class func hashKeyAttribute() -> String {

        return "_courseLevelID"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_courseLevelID" : "courseLevelID",
               "_subject" : "subject",
               "_year" : "year",
        ]
    }
}
