//
//  StudentMain.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class StudentMain: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _appleIDemail: String?
    var _appleIDverficationCode: String?
    var _appleIDverficationDate: String?
    var _rating: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "tutortonight-mobilehub-1959870186-student_main"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_appleIDemail" : "appleIDemail",
               "_appleIDverficationCode" : "appleIDverficationCode",
               "_appleIDverficationDate" : "appleIDverficationDate",
               "_rating" : "rating",
        ]
    }
}
