//
//  TutorGrades.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class TutorGrades: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _courseNumber: NSNumber?
    var _courseSubject: String?
    var _dateCompleted: String?
    var _grade: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "tutortonight-mobilehub-1959870186-tutor_grades"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_courseNumber" : "courseNumber",
               "_courseSubject" : "courseSubject",
               "_dateCompleted" : "dateCompleted",
               "_grade" : "grade",
        ]
    }
}
