//
//  UniversityMain.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB

class UniversityMain: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _city: String?
    var _domain: String?
    var _name: String?
    var _postalCode: String?
    var _province: String?
    var _street: String?
    
    class func dynamoDBTableName() -> String {

        return "tutortonight-mobilehub-1959870186-university_main"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_city" : "city",
               "_domain" : "domain",
               "_name" : "name",
               "_postalCode" : "postalCode",
               "_province" : "province",
               "_street" : "street",
        ]
    }
}
