//
//  SessionPendingTable.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.4
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSMobileHubHelper

class SessionPendingTable: NSObject, Table {
    
    var tableName: String
    var partitionKeyName: String
    var partitionKeyType: String
    var sortKeyName: String?
    var sortKeyType: String?
    var model: AWSDynamoDBObjectModel
    var indexes: [Index]
    var orderedAttributeKeys: [String] {
        return produceOrderedAttributeKeys(model)
    }
    var tableDisplayName: String {

        return "session_pending"
    }
    
    override init() {

        model = SessionPending()
        
        tableName = model.classForCoder.dynamoDBTableName()
        partitionKeyName = model.classForCoder.hashKeyAttribute()
        partitionKeyType = "Number"
        indexes = [

            SessionPendingSessionID(),
        ]
        if (model.classForCoder.respondsToSelector("rangeKeyAttribute")) {
            sortKeyName = model.classForCoder.rangeKeyAttribute!()
        }
        super.init()
    }
    
    /**
     * Converts the attribute name from data object format to table format.
     *
     * - parameter dataObjectAttributeName: data object attribute name
     * - returns: table attribute name
     */

    func tableAttributeName(dataObjectAttributeName: String) -> String {
        return SessionPending.JSONKeyPathsByPropertyKey()[dataObjectAttributeName] as! String
    }
    
    func getItemDescription() -> String {
        return "Find Item with sessionID = \(1111500000)."
    }
    
    func getItemWithCompletionHandler(completionHandler: (response: AWSDynamoDBObjectModel?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        objectMapper.load(SessionPending.self, hashKey: 1111500000, rangeKey: nil, completionHandler: {(response: AWSDynamoDBObjectModel?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func scanDescription() -> String {
        return "Show all items in the table."
    }
    
    func scanWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let scanExpression = AWSDynamoDBScanExpression()
        scanExpression.limit = 5

        objectMapper.scan(SessionPending.self, expression: scanExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func scanWithFilterDescription() -> String {
        return "Find all items with courseCode < \("demo-courseCode-500000")."
    }
    
    func scanWithFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let scanExpression = AWSDynamoDBScanExpression()
        
        scanExpression.filterExpression = "#courseCode < :courseCode"
        scanExpression.expressionAttributeNames = ["#courseCode": "courseCode" ,]
        scanExpression.expressionAttributeValues = [":courseCode": "demo-courseCode-500000" ,]

        objectMapper.scan(SessionPending.self, expression: scanExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func insertSampleDataWithCompletionHandler(completionHandler: (errors: [NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        var errors: [NSError] = []
        let group: dispatch_group_t = dispatch_group_create()
        let numberOfObjects = 20
        

        let itemForGet = SessionPending()
        
        itemForGet._sessionID = 1111500000
        itemForGet._courseCode = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("courseCode")
        itemForGet._courseSubject = NoSQLSampleDataGenerator.randomSampleNumber()
        itemForGet._endTime = NoSQLSampleDataGenerator.randomSampleNumber()
        itemForGet._location = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("location")
        itemForGet._notes = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("notes")
        itemForGet._startTime = NoSQLSampleDataGenerator.randomSampleNumber()
        itemForGet._student = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("student")
        itemForGet._studentRequestedTime = NoSQLSampleDataGenerator.randomSampleNumber()
        itemForGet._tutor = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("tutor")
        itemForGet._tutorAcceptedTime = NoSQLSampleDataGenerator.randomSampleNumber()
        
        
        dispatch_group_enter(group)
        

        objectMapper.save(itemForGet, completionHandler: {(error: NSError?) -> Void in
            if error != nil {
                dispatch_async(dispatch_get_main_queue(), {
                    errors.append(error!)
                })
            }
            dispatch_group_leave(group)
        })
        
        for _ in 1..<numberOfObjects {

            let item: SessionPending = SessionPending()
            item._sessionID = NoSQLSampleDataGenerator.randomSampleNumber()
            item._courseCode = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("courseCode")
            item._courseSubject = NoSQLSampleDataGenerator.randomSampleNumber()
            item._endTime = NoSQLSampleDataGenerator.randomSampleNumber()
            item._location = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("location")
            item._notes = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("notes")
            item._startTime = NoSQLSampleDataGenerator.randomSampleNumber()
            item._student = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("student")
            item._studentRequestedTime = NoSQLSampleDataGenerator.randomSampleNumber()
            item._tutor = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("tutor")
            item._tutorAcceptedTime = NoSQLSampleDataGenerator.randomSampleNumber()
            
            dispatch_group_enter(group)
            
            objectMapper.save(item, completionHandler: {(error: NSError?) -> Void in
                if error != nil {
                    dispatch_async(dispatch_get_main_queue(), {
                        errors.append(error!)
                    })
                }
                dispatch_group_leave(group)
            })
        }
        
        dispatch_group_notify(group, dispatch_get_main_queue(), {
            if errors.count > 0 {
                completionHandler(errors: errors)
            }
            else {
                completionHandler(errors: nil)
            }
        })
    }
    
    func removeSampleDataWithCompletionHandler(completionHandler: (errors: [NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let scanExpression = AWSDynamoDBScanExpression()
        scanExpression.filterExpression = "#sessionID >= :sessionID"
        scanExpression.expressionAttributeNames = ["#sessionID": "sessionID"]
        scanExpression.expressionAttributeValues = [":sessionID": 1111000000]

        objectMapper.scan(SessionPending.self, expression: scanExpression) { (response: AWSDynamoDBPaginatedOutput?, error: NSError?) in
            if let error = error {
                dispatch_async(dispatch_get_main_queue(), {
                    completionHandler(errors: [error]);
                    })
            } else {
                var errors: [NSError] = []
                let group: dispatch_group_t = dispatch_group_create()
                for item in response!.items {
                    dispatch_group_enter(group)
                    objectMapper.remove(item, completionHandler: {(error: NSError?) -> Void in
                        if error != nil {
                            dispatch_async(dispatch_get_main_queue(), {
                                errors.append(error!)
                            })
                        }
                        dispatch_group_leave(group)
                    })
                }
                dispatch_group_notify(group, dispatch_get_main_queue(), {
                    if errors.count > 0 {
                        completionHandler(errors: errors)
                    }
                    else {
                        completionHandler(errors: nil)
                    }
                })
            }
        }
    }
    
    func updateItem(item: AWSDynamoDBObjectModel, completionHandler: (error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        

        let itemToUpdate: SessionPending = item as! SessionPending
        
        itemToUpdate._courseCode = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("courseCode")
        itemToUpdate._courseSubject = NoSQLSampleDataGenerator.randomSampleNumber()
        itemToUpdate._endTime = NoSQLSampleDataGenerator.randomSampleNumber()
        itemToUpdate._location = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("location")
        itemToUpdate._notes = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("notes")
        itemToUpdate._startTime = NoSQLSampleDataGenerator.randomSampleNumber()
        itemToUpdate._student = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("student")
        itemToUpdate._studentRequestedTime = NoSQLSampleDataGenerator.randomSampleNumber()
        itemToUpdate._tutor = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("tutor")
        itemToUpdate._tutorAcceptedTime = NoSQLSampleDataGenerator.randomSampleNumber()
        
        objectMapper.save(itemToUpdate, completionHandler: {(error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(error: error)
            })
        })
    }
    
    func removeItem(item: AWSDynamoDBObjectModel, completionHandler: (error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        
        objectMapper.remove(item, completionHandler: {(error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(error: error)
            })
        })
    }
}

class SessionPendingSessionID: NSObject, Index {
    
    var indexName: String? {

        return "sessionID"
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        return "Find all items with sessionID = \(1111000003)."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "sessionID"
        queryExpression.keyConditionExpression = "#sessionID = :sessionID"
        queryExpression.expressionAttributeNames = ["#sessionID": "sessionID",]
        queryExpression.expressionAttributeValues = [":sessionID": 1111000003,]

        objectMapper.query(SessionPending.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        return "Find all items with sessionID = \(1111000003) and courseCode > \("demo-courseCode-500000")."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(completionHandler: (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.defaultDynamoDBObjectMapper()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "sessionID"
        queryExpression.keyConditionExpression = "#sessionID = :sessionID"
        queryExpression.filterExpression = "#courseCode > :courseCode"
        queryExpression.expressionAttributeNames = [
            "#sessionID": "sessionID",
            "#courseCode": "courseCode",
        ]
        queryExpression.expressionAttributeValues = [
            ":sessionID": 1111000003,
            ":courseCode": "demo-courseCode-500000",
        ]
        

        objectMapper.query(SessionPending.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            dispatch_async(dispatch_get_main_queue(), {
                completionHandler(response: response, error: error)
            })
        })
    }
    
}
